import { StyleSheet } from "react-native";
import { cardTiers, colors, modalLayout, radius, shadow, spacing, typography } from "./tokens.js";

const layout = {
  screenMaxWidth: 760,
  contentMaxWidth: 720,
  modalMaxWidth: 560,
  modalWideMaxWidth: 680,
  heroMaxWidth: 720,
  startMaxWidth: 560,
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg.base,
  },
  safeScreen: {
    flex: 1,
    backgroundColor: colors.bg.base,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: spacing.lg,
    paddingTop: 50,
    paddingBottom: spacing.md,
  },
  headerRightSection: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  nameText: {
    fontSize: 26,
    fontWeight: "800",
    color: colors.text.primary,
  },
  subtitleText: {
    fontSize: typography.label,
    color: colors.text.secondary,
    marginTop: spacing.xxs,
  },
  moneyText: {
    fontSize: 22,
    fontWeight: "800",
    color: colors.brand.primary,
  },
  statsCard: {
    backgroundColor: cardTiers.primary.backgroundColor,
    marginHorizontal: 0,
    marginVertical: 0,
    padding: spacing.xl,
    borderRadius: radius.lg,
    borderWidth: cardTiers.primary.borderWidth,
    borderColor: cardTiers.primary.borderColor,
    ...shadow.card,
  },
  statsCardEmbedded: {
    backgroundColor: "transparent",
    marginTop: spacing.lg,
    paddingTop: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: colors.border.subtle,
  },
  ageText: {
    fontSize: 22,
    fontWeight: "800",
    color: colors.text.primary,
    marginBottom: spacing.md,
  },
  statRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.sm,
  },
  statLabel: {
    color: colors.text.primary,
    fontSize: typography.body,
    width: 120,
  },
  statBarBg: {
    flex: 1,
    height: 10,
    backgroundColor: colors.status.track,
    borderRadius: radius.pill,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  statBarFill: {
    height: "100%",
    borderRadius: radius.pill,
    backgroundColor: colors.status.positive,
  },
  statBarFillDanger: {
    height: "100%",
    borderRadius: radius.pill,
    backgroundColor: colors.status.warning,
  },
  statValue: {
    color: colors.text.secondary,
    fontSize: typography.label,
    marginLeft: spacing.sm,
    width: 50,
    textAlign: "right",
  },
  inlineMetricRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.sm,
  },
  inlineMetricLabel: {
    color: colors.text.primary,
    fontSize: typography.body,
    minWidth: 76,
    marginRight: spacing.sm,
  },
  inlineMetricTrack: {
    flex: 1,
    height: 10,
    backgroundColor: colors.status.track,
    borderRadius: radius.pill,
    overflow: "hidden",
  },
  inlineMetricFill: {
    height: "100%",
    borderRadius: radius.pill,
    backgroundColor: colors.status.warning,
  },
  inlineMetricValue: {
    color: colors.text.secondary,
    fontSize: typography.label,
    fontWeight: "700",
    marginLeft: spacing.sm,
    minWidth: 44,
    textAlign: "right",
  },
  gradeMetricValue: {
    minWidth: 72,
  },
  tabBar: {
    flexDirection: "row",
    backgroundColor: colors.surface.cardMuted,
    paddingHorizontal: spacing.xs,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  tab: {
    flex: 1,
    paddingVertical: spacing.sm,
    alignItems: "center",
    borderRadius: radius.md,
  },
  tabActive: {
    backgroundColor: colors.brand.primary,
  },
  tabText: {
    color: colors.text.secondary,
    fontSize: typography.label,
    fontWeight: "700",
  },
  content: {
    flex: 1,
    padding: spacing.lg,
    width: "100%",
    maxWidth: layout.contentMaxWidth,
    alignSelf: "center",
  },
  sectionTitle: {
    fontSize: typography.titleMd,
    fontWeight: "800",
    color: colors.text.primary,
    marginBottom: spacing.md,
    letterSpacing: 0.1,
  },
  subsectionTitle: {
    fontSize: typography.titleSm,
    fontWeight: "800",
    color: colors.text.primary,
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
  },
  historyBlock: {
    marginBottom: spacing.lg,
  },
  historyAge: {
    fontSize: typography.titleSm,
    fontWeight: "800",
    color: colors.brand.primary,
    marginBottom: spacing.xs,
  },
  historyEvent: {
    fontSize: typography.body,
    color: colors.text.secondary,
    marginBottom: spacing.xxs,
    lineHeight: 22,
  },
  section: {
    marginBottom: spacing.xl,
  },
  helperText: {
    fontSize: typography.label,
    color: colors.text.secondary,
    marginBottom: spacing.sm,
    lineHeight: 18,
  },
  helperTextSuccess: {
    color: colors.status.successText,
  },
  helperTextDanger: {
    color: colors.text.warm,
  },
  helperTextReward: {
    color: colors.brand.primary,
  },
  helperTextInfo: {
    color: colors.text.accent,
  },
  personCard: {
    backgroundColor: colors.surface.card,
    padding: spacing.md,
    borderRadius: radius.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  personCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  personCardCopy: {
    flex: 1,
  },
  personCardMetricRow: {
    marginTop: spacing.sm,
  },
  personName: {
    fontSize: typography.bodyLarge,
    fontWeight: "800",
    color: colors.text.primary,
  },
  personDetail: {
    fontSize: typography.label,
    color: colors.text.secondary,
    marginTop: spacing.xxs,
    lineHeight: 18,
  },
  bondBarSmall: {
    width: 86,
    height: 10,
    backgroundColor: colors.status.track,
    borderRadius: radius.pill,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  bondBarFill: {
    height: "100%",
    backgroundColor: colors.status.bond,
  },
  actionButton: {
    backgroundColor: colors.button.primaryBg,
    paddingVertical: 15,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    marginBottom: spacing.sm,
    alignItems: "center",
    ...shadow.card,
  },
  actionButtonDanger: {
    backgroundColor: colors.button.destructiveBg,
    paddingVertical: 15,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    marginBottom: spacing.sm,
    alignItems: "center",
    ...shadow.card,
  },
  actionButtonSecondary: {
    backgroundColor: colors.button.secondaryBg,
    paddingVertical: 15,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    marginBottom: spacing.sm,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.button.secondaryBorder,
  },
  actionButtonText: {
    color: colors.button.primaryText,
    fontSize: typography.bodyLarge,
    fontWeight: "800",
  },
  actionButtonSubtext: {
    color: colors.button.primaryText,
    opacity: 0.78,
    fontSize: typography.label,
    lineHeight: 18,
    textAlign: "center",
    marginTop: spacing.xxs,
  },
  actionButtonSecondaryText: {
    color: colors.button.secondaryText,
    fontSize: typography.bodyLarge,
    fontWeight: "800",
  },
  actionButtonMuted: {
    backgroundColor: colors.ui.secondary,
    paddingVertical: 15,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    marginBottom: spacing.sm,
    alignItems: "center",
    ...shadow.card,
  },
  actionButtonInfo: {
    backgroundColor: colors.button.tertiaryBg,
    paddingVertical: 15,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    marginBottom: spacing.sm,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  actionButtonInfoText: {
    color: colors.button.tertiaryText,
    fontSize: typography.bodyLarge,
    fontWeight: "800",
  },
  actionButtonDisabled: {
    backgroundColor: colors.ui.disabled,
    opacity: 0.72,
  },
  ageButtonText: {
    color: colors.button.primaryText,
    fontSize: 22,
    fontWeight: "800",
  },
  ageButtonSubtext: {
    color: colors.button.primaryText,
    opacity: 0.78,
    fontSize: typography.label,
    marginTop: spacing.xxs,
  },
  title: {
    fontSize: 32,
    fontWeight: "800",
    color: colors.text.primary,
    textAlign: "center",
    lineHeight: 40,
  },
  startButton: {
    backgroundColor: colors.button.primaryBg,
    paddingVertical: 18,
    paddingHorizontal: spacing.xl,
    marginTop: spacing.xl,
    borderRadius: radius.md,
    alignItems: "center",
    ...shadow.card,
  },
  startButtonText: {
    color: colors.button.primaryText,
    fontSize: typography.titleSm,
    fontWeight: "800",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.bg.overlayStrong,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: spacing.md,
    paddingTop: spacing.xxl + spacing.md,
    paddingBottom: spacing.xl,
  },
  modalCard: {
    backgroundColor: colors.bg.elevated,
    width: "100%",
    maxWidth: layout.modalMaxWidth,
    alignSelf: "center",
    padding: spacing.xl,
    maxHeight: modalLayout.maxHeight,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    ...shadow.modal,
  },
  modalContainer: {
    backgroundColor: colors.bg.elevated,
    width: "100%",
    maxWidth: layout.modalWideMaxWidth,
    alignSelf: "center",
    maxHeight: modalLayout.wideMaxHeight,
    padding: spacing.lg,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    ...shadow.modal,
  },
  modalTitle: {
    fontSize: typography.titleMd,
    fontWeight: "800",
    color: colors.text.primary,
    marginBottom: spacing.xs,
    textAlign: "center",
  },
  modalSubtitle: {
    fontSize: typography.body,
    color: colors.text.secondary,
    textAlign: "center",
    marginBottom: spacing.lg,
    lineHeight: 21,
  },
  modalDescription: {
    fontSize: typography.body,
    color: colors.text.secondary,
    textAlign: "center",
    marginBottom: spacing.lg,
    lineHeight: 21,
  },
  modalHeader: {
    paddingBottom: spacing.sm,
    alignItems: "center",
  },
  modalStatusText: {
    fontSize: typography.label,
    color: colors.text.secondary,
    textAlign: "center",
    marginTop: spacing.xxs,
    lineHeight: 18,
  },
  modalScrollBody: {
    flexGrow: 0,
    flexShrink: 1,
    maxHeight: "64%",
    marginBottom: spacing.sm,
  },
  modalScrollContent: {
    paddingBottom: spacing.xxl,
  },
  modalFooter: {
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border.subtle,
    gap: spacing.sm,
    backgroundColor: colors.bg.elevated,
  },
  input: {
    backgroundColor: colors.bg.elevated,
    color: colors.text.primary,
    padding: spacing.sm,
    borderRadius: radius.md,
    marginBottom: spacing.md,
    fontSize: typography.bodyLarge,
    borderWidth: 1,
    borderColor: colors.border.strong,
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: spacing.lg,
    gap: spacing.sm,
  },
  smallButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: spacing.sm,
    backgroundColor: colors.button.secondaryBg,
    borderRadius: radius.md,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  smallButtonActive: {
    backgroundColor: colors.brand.primarySoft,
    borderColor: colors.brand.primary,
  },
  smallButtonText: {
    color: colors.text.primary,
    fontSize: typography.label,
    fontWeight: "700",
  },
  createButton: {
    backgroundColor: colors.button.primaryBg,
    padding: spacing.md,
    borderRadius: radius.md,
    alignItems: "center",
    ...shadow.card,
  },
  createButtonText: {
    color: colors.button.primaryText,
    fontSize: typography.titleSm,
    fontWeight: "800",
  },
  closeButton: {
    backgroundColor: colors.button.tertiaryBg,
    padding: 15,
    borderRadius: radius.md,
    alignItems: "center",
    marginBottom: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  closeButtonText: {
    color: colors.button.tertiaryText,
    fontSize: typography.bodyLarge,
    fontWeight: "700",
  },
  gigDescription: {
    fontSize: typography.bodyLarge,
    color: colors.text.secondary,
    textAlign: "center",
    marginBottom: spacing.sm,
  },
  gigPay: {
    fontSize: typography.body,
    color: colors.text.accent,
    textAlign: "center",
    marginBottom: spacing.xs,
  },
  gigTotal: {
    fontSize: typography.titleSm,
    color: colors.text.accent,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: spacing.lg,
  },
  randomizeButton: {
    backgroundColor: colors.button.secondaryBg,
    padding: 14,
    borderRadius: radius.md,
    alignItems: "center",
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.button.secondaryBorder,
  },
  utilityInlineButton: {
    alignSelf: "flex-end",
    backgroundColor: colors.button.secondaryBg,
    borderRadius: radius.pill,
    paddingVertical: 8,
    paddingHorizontal: spacing.sm + 2,
    borderWidth: 1,
    borderColor: colors.button.secondaryBorder,
    marginTop: spacing.xs,
  },
  utilityInlineButtonText: {
    color: colors.button.secondaryText,
    fontSize: typography.label,
    fontWeight: "700",
  },
  schoolMenuItem: {
    backgroundColor: colors.surface.cardMuted,
    padding: spacing.md,
    borderRadius: radius.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  schoolMenuText: {
    color: colors.text.primary,
    fontSize: typography.bodyLarge,
    fontWeight: "700",
  },
  activityHeaderText: {
    color: colors.text.primary,
    fontSize: typography.bodyLarge,
    fontWeight: "700",
  },
  popularityBar: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: spacing.sm,
    marginBottom: spacing.md,
  },
  popularityLabel: {
    color: colors.text.primary,
    fontSize: typography.body,
    marginRight: spacing.sm,
  },
  popularityBarBg: {
    flex: 1,
    height: 8,
    backgroundColor: colors.status.track,
    borderRadius: radius.pill,
    overflow: "hidden",
  },
  popularityBarFill: {
    height: "100%",
    backgroundColor: colors.accent.reward,
    borderRadius: radius.pill,
  },
  limitWarning: {
    fontSize: typography.label,
    color: colors.text.warm,
    marginTop: spacing.xxs,
    textAlign: "center",
  },
  settingsButton: {
    padding: spacing.sm,
    backgroundColor: colors.button.secondaryBg,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  settingsButtonText: {
    color: colors.button.secondaryText,
    fontSize: typography.bodyLarge,
    fontWeight: "800",
  },
  modalCardLarge: {
    backgroundColor: colors.bg.elevated,
    width: "100%",
    maxWidth: layout.modalWideMaxWidth,
    maxHeight: "84%",
    padding: spacing.xl,
    borderRadius: radius.lg,
    alignSelf: "center",
    borderWidth: 1,
    borderColor: colors.border.subtle,
    ...shadow.modal,
  },
  lifeCard: {
    backgroundColor: colors.surface.cardMuted,
    padding: spacing.md,
    borderRadius: radius.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  lifeCardSelectArea: {
    flex: 1,
  },
  lifeCardMetaBlock: {
    marginTop: spacing.xs,
    marginBottom: spacing.md,
  },
  lifeCardActions: {
    paddingTop: spacing.xs,
    borderTopWidth: 1,
    borderTopColor: colors.border.subtle,
  },
  extracurricularCard: {
    backgroundColor: colors.surface.card,
    padding: spacing.sm + 2,
    borderRadius: radius.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  disabledCard: {
    backgroundColor: colors.ui.disabled,
    opacity: 0.6,
  },
  extracurricularTitle: {
    color: colors.text.primary,
    fontSize: typography.body,
    fontWeight: "700",
    marginBottom: spacing.xxs,
  },
  extracurricularDesc: {
    color: colors.text.secondary,
    fontSize: typography.label,
    lineHeight: 18,
  },
  accordionHeader: {
    backgroundColor: colors.surface.cardMuted,
    padding: spacing.md,
    borderRadius: radius.md,
    marginBottom: spacing.xs,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  accordionContent: {
    backgroundColor: colors.surface.card,
    padding: spacing.sm + 2,
    borderRadius: radius.md,
    marginTop: spacing.xxs,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  accordionItem: {
    backgroundColor: colors.bg.raised,
    padding: spacing.sm,
    borderRadius: radius.sm,
    marginBottom: spacing.xs,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  accordionItemText: {
    color: colors.text.primary,
    fontSize: typography.body,
  },
  accordionSubheader: {
    color: colors.brand.primary,
    fontSize: typography.label,
    fontWeight: "700",
    marginTop: spacing.sm,
    marginBottom: spacing.xxs,
    marginLeft: spacing.xxs,
  },
  jobCard: {
    backgroundColor: colors.surface.card,
    padding: spacing.md,
    borderRadius: radius.md,
    marginBottom: spacing.sm + 2,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  jobTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: colors.text.primary,
    marginBottom: spacing.xxs,
  },
  jobDescription: {
    fontSize: typography.label,
    color: colors.text.secondary,
    marginBottom: spacing.sm,
    lineHeight: 18,
  },
  jobDetail: {
    fontSize: typography.label,
    color: colors.text.secondary,
    marginBottom: spacing.xxs,
  },
  jobRequirementsTitle: {
    fontSize: typography.label,
    fontWeight: "700",
    color: colors.brand.primary,
    marginTop: spacing.xs,
    marginBottom: spacing.xxs,
  },
  jobRequirement: {
    fontSize: 12,
    color: colors.text.secondary,
    marginLeft: spacing.xs,
    marginBottom: 2,
  },
  ineligibleBadge: {
    backgroundColor: colors.surface.cardWarm,
    padding: spacing.sm,
    borderRadius: radius.sm,
    marginTop: spacing.sm,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.accent.warm,
  },
  ineligibleText: {
    color: colors.text.warm,
    fontSize: typography.body,
    fontWeight: "700",
  },
  historyCard: {
    backgroundColor: colors.surface.card,
    padding: spacing.sm + 2,
    borderRadius: radius.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  historyTitle: {
    fontSize: typography.body,
    fontWeight: "700",
    color: colors.text.primary,
    marginBottom: spacing.xxs,
  },
  historyDetail: {
    fontSize: typography.label,
    color: colors.text.secondary,
    marginBottom: 2,
  },
  lifeCardName: {
    fontSize: typography.titleSm,
    fontWeight: "800",
    color: colors.text.primary,
    marginBottom: spacing.xxs,
  },
  lifeCardDetail: {
    fontSize: typography.label,
    color: colors.text.secondary,
    marginBottom: 2,
  },
  deleteButton: {
    backgroundColor: colors.button.destructiveBg,
    paddingVertical: spacing.sm + 2,
    paddingHorizontal: spacing.md,
    borderRadius: radius.sm,
    marginTop: spacing.xs,
    justifyContent: "center",
    minWidth: 80,
    alignSelf: "flex-start",
  },
  stressIndicator: {
    backgroundColor: colors.surface.card,
    padding: spacing.md,
    borderRadius: radius.md,
    marginBottom: spacing.lg,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  stressLabel: {
    color: colors.text.primary,
    fontSize: typography.body,
    marginRight: spacing.sm,
    minWidth: 60,
  },
  stressBarContainer: {
    flex: 1,
    height: 10,
    backgroundColor: colors.status.track,
    borderRadius: radius.pill,
    overflow: "hidden",
  },
  stressBarFill: {
    height: "100%",
    backgroundColor: colors.status.warning,
    borderRadius: radius.pill,
  },
  stressValue: {
    color: colors.text.warm,
    fontSize: typography.body,
    fontWeight: "700",
    marginLeft: spacing.sm,
    minWidth: 50,
    textAlign: "right",
  },
  relationshipCategoryHeader: {
    backgroundColor: colors.surface.cardMuted,
    padding: 14,
    borderRadius: radius.md,
    marginBottom: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  relationshipCategoryIcon: {
    fontSize: typography.titleSm,
    marginRight: spacing.xs,
  },
  relationshipCategoryText: {
    color: colors.text.primary,
    fontSize: typography.bodyLarge,
    fontWeight: "700",
  },
  careerCard: {
    backgroundColor: colors.surface.card,
    padding: spacing.lg - 2,
    borderRadius: radius.md,
    marginBottom: spacing.md,
    borderLeftWidth: 4,
    borderLeftColor: colors.brand.primary,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  careerCardDisabled: {
    opacity: 0.56,
    borderLeftColor: colors.ui.secondary,
  },
  careerCardTitle: {
    fontSize: typography.titleSm,
    fontWeight: "800",
    color: colors.text.primary,
    marginBottom: spacing.xs,
  },
  careerCardDescription: {
    fontSize: typography.body,
    color: colors.text.secondary,
    marginBottom: spacing.sm,
    lineHeight: 20,
  },
  careerCardDetail: {
    fontSize: typography.label,
    color: colors.text.secondary,
    marginBottom: spacing.xxs + 2,
  },
  careerRequirementMet: {
    fontSize: typography.label,
    color: colors.status.successText,
    marginLeft: spacing.xs,
    marginBottom: spacing.xxs,
  },
  careerRequirementNotMet: {
    fontSize: typography.label,
    color: colors.text.warm,
    marginLeft: spacing.xs,
    marginBottom: spacing.xxs,
  },
  careerWarningBadge: {
    backgroundColor: colors.surface.cardReward,
    padding: spacing.xs,
    borderRadius: radius.sm,
    marginTop: spacing.xs,
    marginBottom: spacing.xs,
    borderLeftWidth: 3,
    borderLeftColor: colors.accent.reward,
  },
  careerDangerBadge: {
    backgroundColor: colors.surface.cardWarm,
    padding: spacing.xs,
    borderRadius: radius.sm,
    marginTop: spacing.xs,
    marginBottom: spacing.xs,
    borderLeftWidth: 3,
    borderLeftColor: colors.accent.warm,
  },
  careerBadgeText: {
    fontSize: typography.label,
    color: colors.text.primary,
    fontWeight: "600",
  },
  startScreenCard: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xxl + spacing.lg,
    paddingBottom: spacing.xxl,
    width: "100%",
    maxWidth: layout.startMaxWidth,
    alignSelf: "center",
  },
  startEyebrow: {
    color: colors.text.accent,
    fontSize: 14,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    textAlign: "center",
    marginBottom: spacing.sm,
  },
  startScreenBody: {
    color: colors.text.secondary,
    fontSize: typography.bodyLarge,
    lineHeight: 26,
    textAlign: "center",
    marginTop: spacing.md,
  },
  floatingAgeButton: {
    position: "absolute",
    left: spacing.lg,
    right: spacing.lg,
    bottom: spacing.xl,
    maxWidth: layout.contentMaxWidth,
    alignSelf: "center",
    backgroundColor: colors.button.primaryBg,
    paddingVertical: 12,
    paddingHorizontal: spacing.lg,
    borderRadius: radius.lg,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border.inverse,
    ...shadow.floating,
  },
  floatingAgeDock: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 120,
    backgroundColor: "rgba(230, 225, 221, 0.84)",
    borderTopWidth: 1,
    borderTopColor: colors.border.subtle,
  },
  feedScroll: {
    flex: 1,
  },
  feedContent: {
    width: "100%",
    maxWidth: layout.contentMaxWidth,
    alignSelf: "center",
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxl,
    paddingBottom: 146,
  },
  heroCard: {
    backgroundColor: cardTiers.primary.backgroundColor,
    borderRadius: radius.lg,
    padding: spacing.xl,
    borderWidth: cardTiers.primary.borderWidth,
    borderColor: cardTiers.primary.borderColor,
    marginBottom: spacing.lg,
    width: "100%",
    maxWidth: layout.heroMaxWidth,
    alignSelf: "center",
    ...shadow.card,
  },
  heroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.md,
  },
  heroIdentity: {
    flex: 1,
  },
  heroName: {
    fontSize: typography.titleLg,
    fontWeight: "800",
    color: colors.text.primary,
  },
  heroMeta: {
    color: colors.text.secondary,
    fontSize: typography.body,
    marginTop: spacing.xs,
  },
  heroSubMeta: {
    color: colors.text.muted,
    fontSize: 14,
    marginTop: spacing.xxs,
  },
  heroActions: {
    alignItems: "flex-end",
  },
  heroMoney: {
    color: colors.brand.primary,
    fontSize: 24,
    fontWeight: "800",
  },
  heroSettingsButton: {
    marginTop: spacing.sm,
    backgroundColor: colors.button.secondaryBg,
    borderRadius: radius.pill,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: colors.button.secondaryBorder,
  },
  heroSettingsButtonText: {
    color: colors.button.secondaryText,
    fontSize: typography.label,
    fontWeight: "700",
  },
  heroProfileButton: {
    marginTop: spacing.lg - 2,
    backgroundColor: colors.button.secondaryBg,
    borderRadius: radius.md,
    paddingVertical: 14,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: colors.button.secondaryBorder,
  },
  heroProfileButtonText: {
    color: colors.button.secondaryText,
    fontSize: typography.body,
    fontWeight: "800",
    textAlign: "center",
  },
  heroStatsWrap: {
    marginTop: spacing.lg,
  },
  chipRail: {
    marginBottom: spacing.xs,
  },
  chipRailContent: {
    paddingRight: spacing.lg,
    paddingLeft: 2,
  },
  chipRailWrap: {
    marginBottom: spacing.lg,
  },
  chipRailHintRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.xs,
  },
  chipRailHint: {
    color: colors.text.muted,
    fontSize: typography.label,
    fontWeight: "700",
  },
  chipRailTail: {
    width: spacing.md,
  },
  quickChip: {
    backgroundColor: colors.button.secondaryBg,
    borderRadius: radius.pill,
    paddingVertical: 11,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: colors.button.secondaryBorder,
    marginRight: spacing.sm,
  },
  quickChipText: {
    color: colors.button.secondaryText,
    fontSize: typography.body,
    fontWeight: "700",
  },
  feedSection: {
    marginBottom: spacing.xl,
  },
  feedSectionEyebrow: {
    color: colors.text.muted,
    fontSize: typography.eyebrow,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: spacing.sm,
  },
  feedSectionTitle: {
    color: colors.text.primary,
    fontSize: typography.titleMd,
    fontWeight: "800",
    marginBottom: spacing.sm + 2,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionLink: {
    color: colors.brand.primary,
    fontSize: typography.body,
    fontWeight: "700",
  },
  feedCard: {
    backgroundColor: colors.surface.card,
    borderRadius: radius.md,
    padding: spacing.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    ...shadow.card,
  },
  feedCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  feedCardCopy: {
    flex: 1,
  },
  feedCardTitle: {
    color: colors.text.primary,
    fontSize: 17,
    fontWeight: "800",
  },
  feedCardSummary: {
    color: colors.text.secondary,
    fontSize: typography.label,
    lineHeight: 20,
    marginTop: spacing.xxs + 1,
  },
  feedCardToggle: {
    color: colors.brand.primary,
    fontSize: typography.label,
    fontWeight: "700",
  },
  feedCardBody: {
    marginTop: spacing.sm + 2,
    paddingTop: spacing.sm + 2,
    borderTopWidth: 1,
    borderTopColor: colors.border.subtle,
  },
  feedCardDetail: {
    color: colors.text.secondary,
    fontSize: typography.label,
    lineHeight: 20,
    marginBottom: spacing.sm,
  },
  feedPrimaryButton: {
    backgroundColor: colors.button.primaryBg,
    borderRadius: radius.md,
    paddingVertical: 15,
    paddingHorizontal: spacing.md,
    alignItems: "center",
    marginBottom: spacing.sm,
  },
  feedPrimaryButtonText: {
    color: colors.button.primaryText,
    fontSize: typography.body,
    fontWeight: "800",
  },
  feedSecondaryButton: {
    backgroundColor: colors.button.secondaryBg,
    borderColor: colors.button.secondaryBorder,
    borderWidth: 1,
    borderRadius: radius.md,
    paddingVertical: 14,
    paddingHorizontal: spacing.md,
    alignItems: "center",
  },
  feedSecondaryButtonText: {
    color: colors.button.secondaryText,
    fontSize: typography.body,
    fontWeight: "700",
  },
  actionCard: {
    backgroundColor: cardTiers.secondary.backgroundColor,
    borderRadius: radius.md,
    padding: spacing.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    ...shadow.card,
  },
  actionCardEyebrow: {
    color: colors.text.muted,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: spacing.xxs + 2,
  },
  actionCardTitle: {
    color: colors.text.primary,
    fontSize: typography.titleSm,
    fontWeight: "800",
  },
  actionCardSummary: {
    color: colors.text.secondary,
    fontSize: typography.body,
    lineHeight: 21,
    marginTop: spacing.xs - 2,
    marginBottom: spacing.md,
  },
  secondaryActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  secondaryActionButton: {
    backgroundColor: colors.button.tertiaryBg,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    borderRadius: radius.sm,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  secondaryActionButtonText: {
    color: colors.button.tertiaryText,
    fontSize: typography.label,
    fontWeight: "700",
  },
  highlightCard: {
    backgroundColor: cardTiers.secondary.backgroundColor,
    borderRadius: radius.md,
    padding: spacing.sm + 2,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    marginBottom: spacing.xs,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  highlightName: {
    color: colors.text.primary,
    fontSize: 17,
    fontWeight: "800",
  },
  highlightMeta: {
    color: colors.text.secondary,
    fontSize: typography.label,
    marginTop: 3,
  },
  highlightBondWrap: {
    alignItems: "flex-end",
    minWidth: 86,
  },
  highlightBondTrack: {
    width: 82,
    height: 8,
    backgroundColor: colors.status.track,
    borderRadius: radius.pill,
    overflow: "hidden",
  },
  highlightBondFill: {
    height: "100%",
    backgroundColor: colors.status.bond,
  },
  highlightBondText: {
    color: colors.text.secondary,
    fontSize: typography.label,
    marginTop: spacing.xxs + 2,
    fontWeight: "700",
  },
  timelineCard: {
    backgroundColor: cardTiers.secondary.backgroundColor,
    borderRadius: radius.md,
    padding: spacing.lg - 2,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    ...shadow.card,
  },
  timelineCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  timelineAge: {
    color: colors.brand.primary,
    fontSize: 17,
    fontWeight: "800",
    marginBottom: spacing.xxs,
  },
  timelineMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: spacing.xs,
  },
  timelineMetaText: {
    color: colors.text.muted,
    fontSize: typography.label,
    fontWeight: "600",
  },
  timelineTag: {
    backgroundColor: colors.accent.cool,
    borderRadius: radius.pill,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  timelineTagText: {
    color: colors.text.accent,
    fontSize: 11,
    fontWeight: "700",
  },
  timelineFeaturedEvent: {
    color: colors.text.primary,
    fontSize: typography.bodyLarge,
    lineHeight: 24,
    fontWeight: "700",
    marginBottom: spacing.sm,
  },
  timelineEvent: {
    color: colors.text.secondary,
    fontSize: typography.label,
    lineHeight: 20,
    marginBottom: spacing.xs - 2,
  },
  timelineCardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: spacing.sm,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.border.subtle,
  },
  timelineOverflowText: {
    color: colors.text.muted,
    fontSize: typography.label,
    fontWeight: "600",
  },
  timelineOpenText: {
    color: colors.text.accent,
    fontSize: typography.label,
    fontWeight: "800",
  },
  timelineOpenPill: {
    backgroundColor: colors.button.secondaryBg,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    borderRadius: radius.pill,
    paddingVertical: 6,
    paddingHorizontal: 11,
  },
  timelineOpenPillText: {
    color: colors.button.secondaryText,
    fontSize: typography.label,
    fontWeight: "700",
  },
  timelineHelperText: {
    color: colors.text.muted,
    fontSize: typography.label,
    marginTop: spacing.xs,
  },
  socialOverviewGrid: {
    gap: spacing.sm,
  },
  socialOverviewCard: {
    backgroundColor: colors.surface.card,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    padding: spacing.md,
    ...shadow.card,
  },
  socialOverviewLabel: {
    color: colors.text.primary,
    fontSize: typography.titleSm,
    fontWeight: "800",
    marginBottom: spacing.xxs,
  },
  socialOverviewValue: {
    color: colors.text.muted,
    fontSize: typography.eyebrow,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  socialOverviewSummary: {
    color: colors.text.secondary,
    fontSize: typography.label,
    marginTop: spacing.xxs,
    lineHeight: 18,
  },
  socialDomainCard: {
    backgroundColor: colors.surface.card,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    padding: spacing.md,
    ...shadow.card,
  },
  socialDomainHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  socialDomainContent: {
    marginTop: spacing.sm,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.border.subtle,
  },
  resultName: {
    color: colors.text.primary,
    fontSize: typography.titleMd,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: spacing.sm,
  },
  resultBody: {
    color: colors.text.secondary,
    fontSize: typography.body,
    textAlign: "center",
    lineHeight: 21,
  },
  resultDelta: {
    color: colors.text.primary,
    fontSize: typography.bodyLarge,
    fontWeight: "800",
    textAlign: "center",
  },
  resultCallout: {
    backgroundColor: colors.surface.cardMuted,
    borderRadius: radius.md,
    padding: spacing.md,
    marginTop: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  resultCalloutText: {
    color: colors.text.secondary,
    fontSize: typography.label,
    textAlign: "center",
    lineHeight: 18,
  },
  milestoneBannerWrap: {
    position: "absolute",
    top: spacing.sm,
    left: spacing.md,
    right: spacing.md,
    zIndex: 40,
    alignItems: "center",
  },
  milestoneBanner: {
    width: "100%",
    maxWidth: layout.screenMaxWidth - spacing.lg,
    backgroundColor: colors.accent.warm,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.accent.warmPressed,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    ...shadow.modal,
  },
  milestoneBannerPressable: {
    width: "100%",
  },
  milestoneBannerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  milestoneBannerEyebrow: {
    color: colors.text.inverse,
    fontSize: typography.eyebrow,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  milestoneBannerTitle: {
    color: colors.text.inverse,
    fontSize: typography.bodyLarge,
    fontWeight: "800",
    flex: 1,
  },
  milestoneBannerDismiss: {
    color: colors.text.inverse,
    fontSize: typography.bodyLarge,
    fontWeight: "800",
  },
  routeScreen: {
    flex: 1,
    backgroundColor: colors.bg.base,
  },
  routeHeader: {
    paddingTop: spacing.xxl,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.sm + 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    maxWidth: layout.screenMaxWidth,
    alignSelf: "center",
  },
  routeBackButton: {
    backgroundColor: colors.button.secondaryBg,
    borderRadius: radius.pill,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: colors.button.secondaryBorder,
  },
  routeBackText: {
    color: colors.button.secondaryText,
    fontSize: typography.label,
    fontWeight: "700",
  },
  routeTitle: {
    color: colors.text.primary,
    fontSize: 24,
    fontWeight: "800",
  },
  routeGhostButton: {
    backgroundColor: colors.button.secondaryBg,
    borderRadius: radius.pill,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: colors.button.secondaryBorder,
  },
  routeGhostButtonText: {
    color: colors.button.secondaryText,
    fontSize: typography.label,
    fontWeight: "700",
  },
  routeContent: {
    flex: 1,
    width: "100%",
    maxWidth: layout.screenMaxWidth,
    alignSelf: "center",
    paddingHorizontal: spacing.lg,
    paddingBottom: 134,
  },
  routeIdentityStrip: {
    width: "100%",
    maxWidth: layout.screenMaxWidth,
    alignSelf: "center",
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.sm,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.subtle,
  },
  routeIdentityName: {
    color: colors.text.primary,
    fontSize: typography.bodyLarge,
    fontWeight: "800",
  },
  routeIdentityMoney: {
    color: colors.brand.primary,
    fontSize: typography.bodyLarge,
    fontWeight: "800",
  },
  accordionSection: {
    marginBottom: spacing.md,
  },
  accordionSectionNested: {
    marginBottom: spacing.sm,
  },
  accordionShellHeader: {
    backgroundColor: colors.surface.cardMuted,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  accordionShellHeaderNested: {
    backgroundColor: colors.surface.card,
    paddingVertical: spacing.sm - 1,
  },
  accordionShellTitleWrap: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  accordionShellTitle: {
    color: colors.text.primary,
    fontSize: typography.bodyLarge,
    fontWeight: "700",
    flexShrink: 1,
  },
  accordionShellRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  accordionShellMeta: {
    color: colors.text.muted,
    fontSize: typography.label,
    fontWeight: "600",
  },
  accordionToggleChip: {
    backgroundColor: colors.button.secondaryBg,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    borderRadius: radius.pill,
    paddingVertical: 5,
    paddingHorizontal: 10,
    minWidth: 54,
    alignItems: "center",
  },
  accordionToggleChipExpanded: {
    backgroundColor: colors.brand.primarySoft,
    borderColor: colors.brand.primary,
  },
  accordionToggleChipText: {
    color: colors.text.muted,
    fontSize: typography.label,
    fontWeight: "700",
  },
  accordionToggleChipTextExpanded: {
    color: colors.brand.primary,
  },
  accordionShellBody: {
    paddingTop: spacing.xs,
  },
  sectionShell: {
    backgroundColor: colors.surface.card,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    padding: spacing.md,
    ...shadow.card,
  },
  stackedButtonGroup: {
    gap: spacing.sm,
  },
  compactList: {
    gap: spacing.sm,
  },
  routeScroll: {
    flex: 1,
  },
  routeScrollContent: {
    width: "100%",
    maxWidth: layout.contentMaxWidth,
    alignSelf: "center",
    paddingTop: spacing.xs,
    paddingBottom: 146,
    paddingHorizontal: spacing.lg,
  },
  panelScrollContent: {
    paddingTop: spacing.xs,
    paddingBottom: 146,
  },
  profileHubSection: {
    marginTop: spacing.lg,
  },
  destinationCardGrid: {
    gap: spacing.sm,
  },
  destinationCard: {
    backgroundColor: cardTiers.secondary.backgroundColor,
    borderRadius: radius.md,
    padding: spacing.lg - 2,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    marginBottom: spacing.sm,
    ...shadow.card,
  },
  destinationCardTitle: {
    color: colors.text.primary,
    fontSize: 17,
    fontWeight: "800",
    marginBottom: spacing.xs - 2,
  },
  destinationCardBody: {
    color: colors.text.secondary,
    fontSize: typography.label,
    lineHeight: 20,
  },
  secondaryPanelButton: {
    backgroundColor: cardTiers.utility.backgroundColor,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.button.secondaryBorder,
    paddingVertical: 15,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.sm,
    alignItems: "center",
  },
  secondaryPanelButtonText: {
    color: colors.button.secondaryText,
    fontSize: typography.body,
    fontWeight: "700",
  },
  placeholderCard: {
    backgroundColor: cardTiers.secondary.backgroundColor,
    borderRadius: radius.lg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    marginBottom: spacing.md,
  },
  placeholderTitle: {
    color: colors.text.primary,
    fontSize: 20,
    fontWeight: "800",
    marginBottom: spacing.sm,
  },
  placeholderBody: {
    color: colors.text.secondary,
    fontSize: typography.body,
    lineHeight: 21,
    marginBottom: spacing.xs,
  },
  assetsSectionLabel: {
    color: colors.text.muted,
    fontSize: typography.eyebrow,
    fontWeight: "800",
    letterSpacing: 1.4,
    textTransform: "uppercase",
    marginBottom: spacing.xs,
  },
  assetsCashValue: {
    color: colors.brand.primary,
    fontSize: typography.titleLg,
    fontWeight: "800",
    marginBottom: spacing.sm,
  },
  divider: {
    height: 1,
    backgroundColor: colors.border.subtle,
    marginVertical: spacing.xs,
  },
  sectionSubtitle: {
    color: colors.text.primary,
    fontSize: typography.body,
    fontWeight: "700",
    marginBottom: spacing.xs,
  },
  activityName: {
    color: colors.text.primary,
    fontSize: typography.bodyLarge,
    fontWeight: "800",
    marginBottom: spacing.xs,
  },
  customizationTabRail: {
    maxHeight: 50,
    marginBottom: spacing.sm + 2,
  },
  customizationTabRailContent: {
    paddingRight: spacing.sm,
  },
  customizationPanel: {
    flex: 1,
    marginBottom: spacing.sm + 2,
    minHeight: 260,
  },
  customizationScroll: {
    flex: 1,
  },
  customizationScrollContent: {
    paddingHorizontal: spacing.xs - 2,
    paddingBottom: spacing.lg,
  },
  customizationSection: {
    marginBottom: spacing.lg - 2,
  },
  customizationFooter: {
    flexDirection: "row",
    gap: spacing.sm,
    paddingTop: spacing.md,
    paddingBottom: spacing.xs,
    borderTopWidth: 1,
    borderTopColor: colors.border.subtle,
  },
  customizationFooterStack: {
    flexDirection: "column",
  },
  footerButton: {
    flex: 1,
  },
  footerButtonStacked: {
    width: "100%",
  },
  colorSwatch: {
    width: 22,
    height: 22,
    borderRadius: radius.pill,
    marginBottom: spacing.xs,
    borderWidth: 1,
    borderColor: colors.border.strong,
  },
  tabButton: {
    paddingVertical: 9,
    paddingHorizontal: spacing.sm,
    marginRight: spacing.xs,
    borderRadius: radius.sm,
    backgroundColor: colors.button.secondaryBg,
    borderWidth: 1,
    borderColor: colors.border.subtle,
  },
  tabButtonActive: {
    backgroundColor: colors.brand.primary,
    borderColor: colors.brand.primary,
  },
  tabButtonText: {
    color: colors.text.secondary,
    fontSize: typography.label,
    fontWeight: "600",
  },
  tabButtonTextActive: {
    color: colors.text.inverse,
    fontWeight: "700",
  },
  feedbackSuccessText: {
    color: colors.status.successText,
  },
  feedbackDangerText: {
    color: colors.text.warm,
  },
  feedbackRewardText: {
    color: colors.brand.primary,
  },
  charCreationCard: {
    backgroundColor: colors.bg.elevated,
    width: "100%",
    maxWidth: layout.modalWideMaxWidth,
    maxHeight: modalLayout.wideMaxHeight,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xl,
    paddingBottom: spacing.lg,
    alignSelf: "center",
    ...shadow.modal,
  },
  charCreationScroll: {
    flexGrow: 0,
  },
  charCreationScrollContent: {
    paddingBottom: spacing.lg,
  },
  charCreationSection: {
    marginBottom: spacing.md,
  },
  charCreationSectionHeader: {
    color: colors.text.muted,
    fontSize: typography.eyebrow,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: spacing.xs,
  },
  charCreationAppearanceSection: {
    marginTop: spacing.xs,
  },
  charCreationPreviewBlock: {
    alignItems: "center",
    marginBottom: spacing.sm,
  },
  charCreationFooter: {
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border.subtle,
    gap: spacing.sm,
  },
  charCreationHalfButton: {
    flex: 1,
    marginBottom: 0,
  },
  compactButtonRow: {
    flexDirection: "column",
  },
  optionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
    marginBottom: spacing.xs,
  },
  optionGridButton: {
    flex: 0,
    flexGrow: 1,
    flexShrink: 1,
    marginBottom: spacing.xs,
    minHeight: 68,
    minWidth: 96,
    justifyContent: "center",
  },
  optionGridButtonCompact: {
    minWidth: "100%",
  },
  characterOptionButton: {
    minWidth: 104,
  },
  characterCustomizerPreviewWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    marginBottom: spacing.md,
    paddingBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.subtle,
  },
  characterCustomizerPreviewWrapCompact: {
    flexDirection: "column",
    alignItems: "center",
  },
  characterCustomizerInfo: {
    flex: 1,
  },
  focusFlashCard: {
    borderColor: colors.accent.warm,
    backgroundColor: colors.surface.cardWarm,
  },
  customizationModalCard: {
    backgroundColor: colors.bg.elevated,
    width: "100%",
    maxWidth: layout.modalWideMaxWidth,
    maxHeight: modalLayout.maxHeight,
    padding: spacing.lg,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    alignSelf: "center",
    ...shadow.modal,
  },
  profileSummary: {
    color: colors.text.secondary,
    fontSize: typography.body,
    lineHeight: 22,
    marginTop: spacing.sm,
  },
  utilityTile: {
    backgroundColor: cardTiers.utility.backgroundColor,
    borderRadius: radius.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: cardTiers.utility.borderColor,
  },
});
